// 🛑 GENERATED BY TILT SDK - DO NOT EDIT
// Source: engine/topologies/tilt/resources/orchestrator/generators/frontend.star
// Purpose: Pre-configured API client for billing resource

import { createApiClient } from '@" + _NPM_SCOPE + "'/platform-api-client';

/**
 * Pre-configured API client for billing resource
 *
 * Usage:
 * ```typescript
 * import { apiClient } from '../.autogenerated/api-client';
 * const data = await apiClient.get('/');
 * ```
 */
export const apiClient = createApiClient({
  baseURL: import.meta.env.VITE_API_URL || 'http://api.tdk-saas-starter.localhost/api/billing-management',
  withAuth: true,
});

export default apiClient;
