///////////////////////////////////////////////////////////////////////////////
// 🛑 CRITICAL: SYSTEM-GENERATED FILE - DO NOT MODIFY DIRECTLY
//
// ANY MANUAL CHANGES MADE TO THIS FILE WILL BE WIPED ON THE NEXT 'tilt up'.
// TO MODIFY THIS CONFIGURATION:
// 1. Edit the source generator in: .tilt/topologies/
// 2. Or update service.json
//
// Generation Source: Vite.Vite.frontend()
// Service: checkout-app
///////////////////////////////////////////////////////////////////////////////

import { resolve } from 'node:path';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';

export default defineConfig({
  base: '/billings/',
  build: {
    cssCodeSplit: false,
    minify: false,
    modulePreload: false,
    rollupOptions: {
      output: {
        entryFileNames: '[name].js',
        format: 'esm',
      },
    },
    target: 'esnext',
  },
  define: {
    global: 'globalThis',
  },
  optimizeDeps: {
    include: [],
  },
  plugins: [react()],
  preview: {
    host: '0.0.0.0',
    port: 3210,
  },
  resolve: {
    alias: {
      // 🎯 IMPORTANT: Order matters! More specific aliases must come FIRST
      '@/autogenerated': resolve(__dirname),
      '@': resolve(__dirname, '../src'),
      'set-cookie-parser': resolve(__dirname, '../src/utils/empty-module.js'),
      // No internal dependencies detected
    },
  },
  server: {
    host: '0.0.0.0',
    port: 3210,
    hmr: {
      port: 4210,
    },
    proxy: {
      '': {
        target: 'http://tdk-saas-starter.localhost/api/billing-management',
        changeOrigin: true,
        secure: false,
      },
      '/health': {
        target: 'http://tdk-saas-starter.localhost/api/billing-management',
        changeOrigin: true,
        secure: false,
      },
      '/trpc': {
        target: 'http://tdk-saas-starter.localhost/api/billing-management',
        changeOrigin: true,
        secure: false,
      },
    },
  },
});
