///////////////////////////////////////////////////////////////////////////////
// 🛑 CRITICAL: SYSTEM-GENERATED FILE - DO NOT MODIFY DIRECTLY
//
// ANY MANUAL CHANGES MADE TO THIS FILE WILL BE WIPED ON THE NEXT 'tilt up'.
// TO MODIFY THIS CONFIGURATION:
// 1. Edit the source generator in: .tilt/topologies/
// 2. Or update service.json
//
// Generation Source: Vite.Vite.frontend()
// Service: checkout-app
// Type: Build-only Vite config
///////////////////////////////////////////////////////////////////////////////

import { resolve } from 'node:path';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';

export default defineConfig({
  mode: 'production',
  base: '/billings/',
  build: {
    cssCodeSplit: false,
    minify: true,
    modulePreload: false,
    rollupOptions: {
      output: {
        entryFileNames: '[name].js',
        format: 'esm',
        // Inline all node_modules to prevent lazy dynamic imports for CJS modules
        manualChunks: undefined,
      },
    },
    target: 'esnext',
  },
  define: {
    global: 'globalThis',
    __DEV__: 'false',
    'process.env.NODE_ENV': '"production"',
  },
  esbuild: {
    // Force production JSX runtime
    jsx: 'automatic',
    jsxImportSource: 'react',
    // CRITICAL: Disable development JSX (jsxDEV) for Vite 8 + Rolldown compatibility
    jsxDev: false,
  },
  optimizeDeps: {
    include: [
      'react',
      'react-dom',
      'react-dom/client',
      'react/jsx-runtime',
      '@tanstack/react-query',
      // Internal packages (auto-generated)
      
    ],
    esbuildOptions: {
      format: 'esm',
      target: 'esnext',
      // Use production JSX runtime
      jsx: 'automatic',
      jsxImportSource: 'react',
      jsxDev: false,
    },
  },
  plugins: [
    react({
      // Force automatic JSX runtime in production mode
      jsxRuntime: 'automatic',
      jsxImportSource: 'react',
    }),
  ],
  resolve: {
    alias: {
      // 🎯 IMPORTANT: Order matters! More specific aliases must come FIRST
      '@/autogenerated': resolve(__dirname),
      '@': resolve(__dirname, '../src'),
      'set-cookie-parser': resolve(__dirname, '../src/utils/empty-module.js'),
      // Force production JSX runtime - alias dev runtime to production runtime
      'react/jsx-dev-runtime': 'react/jsx-runtime',
    },
    conditions: ['browser', 'import', 'module', 'es2020', 'default'],
    mainFields: ['browser', 'module', 'jsnext:main', 'jsnext', 'main'],
  },
});
